/* Generated by automated build script */
#define RELEASE 0.70.2
#define TEXTVER "Release 0.70.2-Sourcetree"
#define SSHVER "PuTTY-Release-0.70.2-Sourcetree"
#define BINARY_VERSION 0,70,2,0
#define SOURCE_COMMIT "c31e8c714729b8e4fe263e112db636e3929a3f72"
