/* Generated by automated build script */
#define RELEASE 0.70.1
#define TEXTVER "Release 0.70.1-Sourcetree"
#define SSHVER "PuTTY-Release-0.70.1-Sourcetree"
#define BINARY_VERSION 0,70,1,0
#define SOURCE_COMMIT "3cd10509a51edf5a21cdc80aabf7e6a934522d47"
